version: "3.7"

services:
  dashboard:
    image: andredevjs/deezy-auto-earn-dashboard:v1.1
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3006:80

  api:
    image: andredevjs/deezy-auto-earn-api:v1.5
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 3007:3007
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      - ${APP_DEEZY_SERVICE_LOGS_DIR}:/app/logs
      - ${APP_DEEZY_SERVICE_CONFIG_DIR}:/app/config
    environment:
      APP_LIGHTNING_NODE_IP: "$APP_LIGHTNING_NODE_IP"
      APP_LIGHTNING_NODE_GRPC_PORT: "$APP_LIGHTNING_NODE_GRPC_PORT"
      TOR_HOST: "$TOR_PROXY_IP"
      TOR_PORT: "$TOR_PROXY_PORT"
      APP_DEEZY_SERVICE_CONFIG_DIR: "/app/config"
      TLS_CERT_PATH: "/lnd/lnd/tls.cert"
      MACAROON_PATH: "/lnd/chain/bitcoin/mainnet/admin.macaroon"

  earn:
    image: andredevjs/deezy-auto-earn:v1.0
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_LIGHTNING_NODE_DATA_DIR}:/lnd:ro
      - ${APP_DEEZY_SERVICE_LOGS_DIR}:/app/logs
      - ${APP_DEEZY_SERVICE_CONFIG_DIR}:/app/config



 # environment:
    #   PROXY_AUTH_ADD: "false"

    # Pass any environment variables to your app for configuration in the form:
    # VARIABLE_NAME: value
    #
    # Here are all the Umbrel provided variables that you can pass through to
    # your app
    # System level environment variables
    # $DEVICE_HOSTNAME - Umbrel server device hostname (e.g. "umbrel")
    # $DEVICE_DOMAIN_NAME - A .local domain name for the Umbrel server (e.g. "umbrel.local")
    #
    # Tor proxy environment variables
    # $TOR_PROXY_IP - Local IP of Tor proxy
    # $TOR_PROXY_PORT - Port of Tor proxy
    #
    # App specific environment variables
    # $APP_HIDDEN_SERVICE - The address of the Tor hidden service your app will be exposed at
    # $APP_PASSWORD - Unique plain text password that can be used for authentication in your app, shown to the user in the Umbrel UI
    # $APP_SEED - Unique 256 bit long hex string (128 bits of entropy) deterministically derived from user's Umbrel seed and your app's ID
  # If your app has more services, like a database container, you can define those
  # services below:
  # db:
  #   image: <docker-image>:<tag>
  #   ...