export APP_DEEZY_SERVICE_DATA_DIR="${EXPORTS_APP_DIR}/data/deezy"
export APP_DEEZY_SERVICE_LOGS_DIR="${APP_DEEZY_SERVICE_DATA_DIR}/logs"
export APP_DEEZY_SERVICE_CONFIG_DIR="${APP_DEEZY_SERVICE_DATA_DIR}/config"